name: appcache
version: 0.1.2
author: João Furtado <jrofurtado@gmail.com>
description: A transformer to generate an appcache file
homepage: https://github.com/jrofurtado/dart-appcache
dependencies:
  barback: any
  code_transformers: any
  html: any
transformers:
- appcache
